# Generated by Django 4.2.1 on 2023-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/project"
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
