# Generated by Django 4.2.1 on 2023-05-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("mail", models.CharField(max_length=50, null=True)),
                ("phone", models.CharField(max_length=15, null=True)),
                ("message", models.TextField(max_length=500, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
