# Generated by Django 4.2.1 on 2023-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_projects_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="images/p1.jpeg", upload_to="media/images"
            ),
        ),
    ]
