# Generated by Django 4.2.1 on 2023-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="images/p1.jpeg", upload_to="images"
            ),
        ),
    ]
