# Generated by Django 4.2.1 on 2023-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="resume",
            field=models.FileField(upload_to="resume/"),
        ),
    ]
