# Generated by Django 4.2.1 on 2023-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
