# Generated by Django 4.2.1 on 2023-07-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_profile_github_profile_linkedin_profile_twitter"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Languages",
            new_name="Services",
        ),
    ]
